#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

[ -n "$CI" ] && exit 0

# PATH="/usr/local/bin:$PATH"
 PATH="~.nvm/versions/node/v18.13.0/bin:$PATH"

# Perform lint check on files in the staging area through .lintstagedrc configuration
pnpm exec lint-staged
